### ISSUE TITLE
Дедлок в TestKitBase.ExpectMsg

### ISSUE THREAD

**Issue by true-zanuda** [Sporteco/EventFly#13]
Пробовал ImmutableHashSet и получал дедлок, заменил на массивы – и дедлок уже появился в другом месте. :)

**Comment by true-zanuda** [comment]
![image](https://user-images.githubusercontent.com/7686621/68181499-2d4cdf00-ffca-11e9-9fa1-c5b203c97442.png)

**Comment by true-zanuda** [comment]
Поэкспериментирую, значит ещё раз...

**Comment by true-zanuda** [comment]
@Larsus , кстати, а что у тебя работает норм? :)

**Comment by Larsus** [comment]
> @Larsus , кстати, а что у тебя работает норм? :)

Ммм, евенты ходят, тесты не упали :)

**Comment by true-zanuda** [comment]
Тесты у нас разные. У меня они проверяют совместную работу нескольких агрегатов.
Возможно, проблема в моих тестах. Надо туда капнуть.

**Comment by anaychenko** [comment]
@Larsus добавит проброс необработанных исключений, возникших в агрегате или менеджере агрегатов, через особый тип результата вызова команды, например UnhandledExceptionCommandResult, в котором будут необработанные исключения

**Comment by true-zanuda** [comment]
Похоже, @Larsus сделал проброс: 680a1986f16f9cdda711072d1aff5196a74745cc.
Сегодня опробую.

**Comment by true-zanuda** [comment]
Не помогло, исключение не выбрасывается.
Саша, воспроизвести можно в моей ветке при прогоне тестов, если что.

**Comment by Larsus** [comment]
@true-zanuda есть некие сложности с перехватом ошибок внутри акки, они попадают в eventstream, делал подписку по типу Error при отправке комманды, но это не даёт результата если вначале ожидать 
ThenExpectDomainEvent а затем ThenExpectReply, все равно получаю ошибку timеout, если же поменять местами то ошибка приходит но тогда никогда не получить domainevent.

**Comment by true-zanuda** [comment]
Решить проблему не удалось, но мы её обошли: возникающие ошибки можно смотреть в output'е теста. Для этого надо использовать конструктор класса теста с передачей `ITestOutputHelper`.
Вот так, например:
```
public TestClass(ITestOutputHelper testOutputHelper) : base(output: testOutputHelper)
{
    ...
}
```
